// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/driver-features/Communications.tsx": () => import("../components/mockups/driver-features/Communications.tsx"),
  "./components/mockups/driver-features/Driving.tsx": () => import("../components/mockups/driver-features/Driving.tsx"),
  "./components/mockups/driver-features/Offline.tsx": () => import("../components/mockups/driver-features/Offline.tsx")
};
